"""Shared ADR 0019 libp2p metric keys for /status / security snapshots (Slice J).

Honesty: these are lab/R&D counters — not a prod mesh cutover signal.
"""

from __future__ import annotations

from typing import Any, Dict, Iterable, Mapping, MutableMapping

# Keys merged from adapter/node metrics into P2PNode._libp2p_status_block.
LIBP2P_STATUS_METRIC_KEYS: tuple[str, ...] = (
    "libp2p_peers",
    "libp2p_dial_ok",
    "libp2p_dial_fail",
    "libp2p_dialing",
    "libp2p_incoming_connection_error",
    "libp2p_peer_external_addr",
    "libp2p_wire_sent",
    "libp2p_wire_recv",
    "libp2p_wire_outbound_failure",
    "libp2p_wire_inbound_failure",
    "libp2p_wire_response_sent",
    "libp2p_wire_response_ok",
    "libp2p_inbound_established",
    "libp2p_incoming_connections",
    "libp2p_connection_closed",
    "libp2p_connection_closed_local",
    "libp2p_connection_closed_io",
    "libp2p_connection_closed_keep_alive",
    "libp2p_established_in_ms_last",
    "libp2p_established_in_ms_max",
    "libp2p_new_listen_addr",
    "libp2p_expired_listen_addr",
    "libp2p_listener_closed",
    "libp2p_listener_error",
    "libp2p_bytes_in",
    "libp2p_bytes_out",
    "libp2p_external_addrs",
    "libp2p_external_addr_confirmed",
    "libp2p_external_addr_expired",
    "libp2p_external_addr_candidates",
    "libp2p_dial_refused_budget",
    "libp2p_gossip_pub",
    "libp2p_gossip_recv",
    "libp2p_mdns_discovered",
    "libp2p_kad_peers",
    "libp2p_kad_queries",
    "libp2p_kad_query_ok",
    "libp2p_kad_query_fail",
    "libp2p_kad_inbound_requests",
    "libp2p_kad_unroutable_peer",
    "libp2p_kad_routable_peer",
    "libp2p_kad_pending_routable_peer",
    "libp2p_kad_mode_changed",
    "libp2p_relay_reservations",
    "libp2p_relay_circuits",
    "libp2p_conn_limit_denied",
    "libp2p_block_denied",
    "libp2p_blocked_peers",
    "libp2p_allow_denied",
    "libp2p_allowed_peers",
    "libp2p_identify_peers",
    "libp2p_identify_received",
    "libp2p_identify_sent",
    "libp2p_identify_pushed",
    "libp2p_identify_error",
    "libp2p_mdns_enabled",
    "libp2p_wire_timeout_secs",
    "libp2p_abs_wire_v1_sent",
    "libp2p_abs_wire_v2_sent",
    "libp2p_abs_wire_v1_recv",
    "libp2p_abs_wire_v2_recv",
    "libp2p_autonat_probes",
    "libp2p_autonat_status_changes",
    "libp2p_autonat_status",
    "libp2p_dcutr_upgrade_success",
    "libp2p_dcutr_upgrade_fail",
    "libp2p_bootstrap_peers",
    "libp2p_bootstrap_dials_ok",
    "libp2p_bootstrap_dials_fail",
    "libp2p_bootstrap_dials_timeout",
    "libp2p_bootstrap_dials_attempted",
    "libp2p_reconnect_scheduled",
    "libp2p_reconnect_ok",
    "libp2p_reconnect_fail",
    "libp2p_reconnect_give_up",
    "libp2p_gossip_validation_accept",
    "libp2p_gossip_validation_reject",
    "libp2p_gossip_app_score_sets",
    "libp2p_gossip_not_supported",
    "libp2p_gossip_peer_subscribed",
    "libp2p_gossip_peer_unsubscribed",
    "libp2p_gossip_peer_score",
    "libp2p_ping_ok",
    "libp2p_ping_fail",
    "libp2p_ping_rtt_ms_last",
    "libp2p_ping_rtt_ms_max",
    "libp2p_ping_unhealthy_disconnects",
    "libp2p_ping_unhealthy_disconnect",
    "libp2p_ping_max_fails",
    "libp2p_ping_max_rtt_ms",
    "libp2p_score_autoblock",
    "libp2p_score_graylist_threshold",
    "libp2p_score_autoblocks",
    "libp2p_score_sweep_ticks",
    "libp2p_peerstore_peers",
    "libp2p_peerstore_learned",
    "libp2p_peerstore_dials_ok",
    "libp2p_peerstore_dials_fail",
    "libp2p_peerstore_dials_timeout",
    "libp2p_peerstore_dials_attempted",
    "libp2p_reconnect_from_peerstore",
    "libp2p_idle_connection_timeout_secs",
    "libp2p_idle_timeout_closes",
    "libp2p_ipv6_listens",
    "libp2p_ipv6_dial_ok",
    "libp2p_rendezvous_registers",
    "libp2p_rendezvous_register_fail",
    "libp2p_rendezvous_discovers",
    "libp2p_rendezvous_discovered_peers",
    "libp2p_rendezvous_discover_fail",
    "libp2p_rendezvous_server_registrations",
    "libp2p_dns_dial_ok",
    "libp2p_dns_dial_fail",
    "libp2p_connection_limits_updates",
    "libp2p_quic_listens",
    "libp2p_quic_dial_ok",
    "libp2p_quic_dial_fail",
    "libp2p_ws_listens",
    "libp2p_ws_dial_ok",
    "libp2p_ws_dial_fail",
    "libp2p_upnp_external_addrs",
    "libp2p_upnp_expired_external_addrs",
    "libp2p_upnp_gateway_not_found",
    "libp2p_upnp_non_routable_gateway",
)


def empty_libp2p_status_metrics() -> Dict[str, int]:
    return {k: 0 for k in LIBP2P_STATUS_METRIC_KEYS}


def merge_libp2p_status_metrics(
    block: MutableMapping[str, Any],
    source: Mapping[str, Any] | None,
    *,
    keys: Iterable[str] = LIBP2P_STATUS_METRIC_KEYS,
) -> None:
    """Copy int metric keys from ``source`` into ``block`` when present."""
    if not source:
        return
    for key in keys:
        if key in source:
            try:
                block[key] = int(source.get(key) or 0)
            except (TypeError, ValueError):
                block[key] = 0
